# Generated by Django 4.2.1 on 2023-05-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_category_additional_json_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='additional_json_data',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
